#!/data/data/com.termux/files/usr/bin/env bash
# ==========================================
# Koshvani Daily Automation
# ==========================================
#
# Two halves, one file (the whole file is parsed before anything runs, so a
# `git pull` that replaces it mid-run cannot corrupt the run that pulled it):
#
#   run_outer     creates a NEW log for this execution (logs/daily-YYYY-MM-DD-HHMMSS.log),
#                 runs the workflow with all its output piped through logsafe.py (nothing
#                 sensitive can reach the log or the screen), and - once that pipeline has
#                 completely drained - commits and pushes the finished log. That happens on
#                 every exit path: success, partial run, no data changes, early failure.
#   run_workflow  the actual job: pull, scrape, commit + push the data, send the Gmail report.
#
# Only explicit paths are ever staged (docs/data, and the execution logs) - never the whole tree.

log()  { echo "$(date '+%Y-%m-%d %H:%M:%S') INFO  [run_daily] $*"; }
warn() { echo "$(date '+%Y-%m-%d %H:%M:%S') WARN  [run_daily] $*"; }

# git_step LABEL COMMAND...   runs a git command and logs its start, exit code and elapsed time
git_step() {
    local label="$1"; shift
    local began; began=$(date +%s)
    log "GIT $label: START"
    "$@"
    local rc=$?
    log "GIT $label: END exit_code=$rc elapsed=$(( $(date +%s) - began ))s"
    return $rc
}

# ==========================================
# The workflow (runs as the "inner" process)
# ==========================================

run_workflow() {

REPO="$HOME/koshvani-dashboard"
cd "$REPO" || exit 1

START_TS="${KOSHVANI_START_TS:-$(date +%s)}"

echo ""
log "========================================"
log "KOSHVANI JOB STARTED"
log "execution_id=$KOSHVANI_EXECUTION_ID log=$KOSHVANI_LOG_FILE"
log "host: $(uname -sr) | $(python --version 2>&1) | $(git --version)"
log "repo: branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null) HEAD=$(git rev-parse --short HEAD 2>/dev/null) dir=$REPO"
log "========================================"


# ==========================================
# Check Git Status
# ==========================================

echo ""
log "[1/6] Checking Git status..."

git status --short

STATUS_FILE="docs/data/crawler_status.json"
if [ -f "$STATUS_FILE" ] && grep -q '"overall_status": "RUNNING"' "$STATUS_FILE"; then
    warn "NOTE: the previous crawler execution never finished (its status file still says RUNNING)."
fi

# docs/data is machine-generated by scrape.py, and the scraper saves every
# scheme the moment it is scraped - so uncommitted changes left by an
# interrupted run (lost signal, Termux killed by Android, ...) are real,
# successfully scraped data, not junk. They used to be discarded here purely so
# that `git pull --rebase` would not refuse to run over unstaged changes; saving
# them as a commit satisfies the pull just as well without destroying anything.
if [ -n "$(git status --porcelain -- docs/data)" ]; then
    warn "Found uncommitted docs/data changes from an interrupted run."
    log "Saving them as a commit instead of discarding them..."
    git_step "add leftover data" git add docs/data
    git_step "commit leftover data" git commit -m "Save partial Koshvani data from an interrupted run"
    if [ $? -ne 0 ]; then
        warn "could not commit the leftover data - leaving it untouched."
    fi
fi

# ==========================================
# Pull Latest Code
# ==========================================

echo ""
log "[2/6] Pulling latest code from GitHub..."

git_step "pull --rebase" git pull --rebase origin main

if [ $? -ne 0 ]; then
    echo ""
    warn "ERROR: Git pull failed."
    warn "Please check Git status."
    # A pull that stopped half way leaves a rebase in progress, which would make every later run fail too.
    GIT_DIR_PATH="$(git rev-parse --git-dir 2>/dev/null)"
    if [ -d "$GIT_DIR_PATH/rebase-merge" ] || [ -d "$GIT_DIR_PATH/rebase-apply" ]; then
        warn "the failed pull left a rebase in progress - aborting it so the repository is usable again"
        git_step "rebase --abort" git rebase --abort
    fi
    log "FINAL STATUS: ERROR (git pull failed)"
    python gmail_alert.py error --start "$START_TS" --stage git-pull
    exit 1
fi

log "Git pull successful."


# ==========================================
# Run Koshvani Scraper
# ==========================================

echo ""
log "[3/6] Starting Koshvani scraper..."

SCRAPER_BEGAN=$(date +%s)
python scraper/scrape.py
SCRAPER_RC=$?
log "SCRAPER END exit_code=$SCRAPER_RC elapsed=$(( $(date +%s) - SCRAPER_BEGAN ))s"

# The scraper exits non-zero only when the run was cut short (a fatal error,
# or it was interrupted). Every scheme it finished was already saved to disk,
# so that is never a reason to throw the data away: it is committed and
# pushed below, and the report says PARTIAL / ERROR.
echo ""
if [ $SCRAPER_RC -eq 0 ]; then
    log "Koshvani scraper completed."
else
    warn "the scraper stopped early (exit code $SCRAPER_RC)."
    log "Everything it had already saved is kept and published below."
fi


# ==========================================
# Check Data Changes
# ==========================================

echo ""
log "[4/6] Checking for data changes..."

# `git status --porcelain` (not `git diff`) so a brand-new, still untracked
# file such as the first crawler_status.json counts as a change too.
if [ -z "$(git status --porcelain -- docs/data)" ]; then

    log "No data changes detected."
    log "No GitHub update required."

    # Nothing left that could still fail before the run is done - safe to
    # validate results and notify now.
    echo ""
    log "Validating scheme results and sending the Gmail report..."
    python gmail_alert.py report --start "$START_TS"
    log "GMAIL report step finished (exit_code=$?)"

    echo ""
    log "========================================"
    if [ $SCRAPER_RC -eq 0 ]; then
        log "KOSHVANI JOB COMPLETED"
        log "FINAL STATUS: SUCCESS - NO DATA CHANGES"
    else
        log "KOSHVANI JOB ENDED EARLY"
        log "FINAL STATUS: INCOMPLETE - scraper exit code $SCRAPER_RC"
    fi
    log "elapsed=$(( $(date +%s) - START_TS ))s"
    log "========================================"

    [ $SCRAPER_RC -eq 0 ] && exit 0
    exit 1
fi

log "Data changes detected:"
git status --short -- docs/data


# ==========================================
# Commit & Push
# ==========================================

echo ""
log "[5/6] Committing updated Koshvani data..."

COMMIT_MESSAGE="Update Koshvani data"
if [ $SCRAPER_RC -ne 0 ]; then
    COMMIT_MESSAGE="Update Koshvani data (partial run - scraper stopped early)"
fi

git_step "add data" git add docs/data

git_step "commit data" git commit -m "$COMMIT_MESSAGE"

if [ $? -ne 0 ]; then
    echo ""
    warn "ERROR: Git commit failed."
    log "FINAL STATUS: ERROR (git commit failed)"
    python gmail_alert.py error --start "$START_TS" --stage git-commit
    exit 1
fi

log "Commit successful: $(git log -1 --format='%h %s')"
git show --shortstat --format= HEAD

echo ""
log "Pushing to GitHub..."

git_step "push data" git push origin main

if [ $? -ne 0 ]; then
    echo ""
    warn "ERROR: Git push failed."
    log "FINAL STATUS: ERROR (git push failed)"
    python gmail_alert.py error --start "$START_TS" --stage git-push
    exit 1
fi

echo ""
log "GitHub push successful: HEAD=$(git rev-parse --short HEAD) origin/main=$(git rev-parse --short origin/main)"


# ==========================================
# Validate Results & Notify
# ==========================================

# Only reached once the run is fully complete (pull, scraper, commit and
# push all done) - so the notification always reflects the real final
# outcome, never a SUCCESS sent before a later step could still fail.
echo ""
log "[6/6] Validating scheme results and sending the Gmail report..."

python gmail_alert.py report --start "$START_TS"
log "GMAIL report step finished (exit_code=$?)"


# ==========================================
# Finished
# ==========================================

echo ""
log "========================================"
if [ $SCRAPER_RC -eq 0 ]; then
    log "KOSHVANI JOB COMPLETED"
    log "FINAL STATUS: SUCCESS"
else
    log "KOSHVANI JOB ENDED EARLY"
    log "FINAL STATUS: INCOMPLETE - partial data was published (scraper exit code $SCRAPER_RC)"
fi
log "elapsed=$(( $(date +%s) - START_TS ))s"
log "========================================"

[ $SCRAPER_RC -eq 0 ] && exit 0
exit 1

}


# ==========================================
# Publishing the execution log (runs in the "outer" process, after the workflow)
# ==========================================

publish_log() {
    cd "$REPO" || return 1
    echo ""
    log "LOG PUBLISH: committing and pushing the execution log"

    # Every finished execution log that is not in git yet: this run's, plus any a
    # previous run could not publish (no network, killed...), plus a single-file daily
    # log left by the previous version of this script. Only files matching this script's
    # naming schemes; each is staged by its own name.
    local files=() f
    while IFS= read -r f; do
        [ -n "$f" ] || continue
        python "$REPO/logsafe.py" --scrub-file "$f"          # last line of defence, in place
        if python "$REPO/logsafe.py" --check "$f"; then
            files+=("$f")
        else
            warn "$f still failed the sanitizer check - NOT publishing it"
        fi
    done < <(git ls-files --others --exclude-standard -- 'logs/daily-????-??-??-??????*.log' 'logs/daily-????-??-??.log')

    if [ ${#files[@]} -eq 0 ]; then
        warn "no execution log to publish"
        return 0
    fi

    git_step "add execution log(s)" git add -- "${files[@]}"
    git_step "commit execution log(s)" git commit -m "Add execution log $KOSHVANI_EXECUTION_ID" -- "${files[@]}"
    if [ $? -ne 0 ]; then
        warn "could not commit the execution log(s); they stay on disk and go out with the next run"
        return 1
    fi

    git_step "push execution log" git push origin main
    if [ $? -ne 0 ]; then
        warn "the log push failed - pulling and retrying once"
        git_step "pull --rebase (retry)" git pull --rebase origin main \
            && git_step "push execution log (retry)" git push origin main
        if [ $? -ne 0 ]; then
            warn "the execution log could not be pushed; it stays committed locally and goes out with the next push"
            python "$REPO/gmail_alert.py" error --start "$KOSHVANI_START_TS" --stage log-push
            return 1
        fi
    fi
    chmod a-w "${files[@]}" 2>/dev/null       # a finished execution's log is never edited again
    log "LOG PUBLISH: pushed ${files[*]} (origin/main=$(git rev-parse --short origin/main))"
}

run_outer() {
    REPO="$HOME/koshvani-dashboard"
    LOG_DIR="$REPO/logs"
    cd "$REPO" || exit 1

    export KOSHVANI_START_TS
    KOSHVANI_START_TS=$(date +%s)
    local stamp; stamp=$(date +%Y-%m-%d-%H%M%S)
    export KOSHVANI_EXECUTION_ID
    KOSHVANI_EXECUTION_ID="$(date +%Y%m%d-%H%M%S)-$(printf '%04x%02x' "$RANDOM" $((RANDOM % 256)))"

    mkdir -p "$LOG_DIR"
    # One log per execution, never reused: the file is created exclusively (noclobber), and
    # a second run in the same second gets a "-2" suffix instead of touching the first one's log.
    LOG_FILE="$LOG_DIR/daily-$stamp.log"
    local n=1
    while ! ( set -o noclobber; : > "$LOG_FILE" ) 2>/dev/null; do
        n=$((n + 1))
        if [ $n -gt 50 ]; then echo "cannot create an execution log in $LOG_DIR" >&2; exit 1; fi
        LOG_FILE="$LOG_DIR/daily-$stamp-$n.log"
    done
    export KOSHVANI_LOG_FILE="logs/$(basename "$LOG_FILE")"

    # Everything the workflow prints (stdout and stderr) passes through the sanitizer on its way
    # to both the screen and the log file; when the pipeline ends the log is complete.
    KOSHVANI_INNER=1 bash "$REPO/run_daily.sh" 2>&1 | python -u "$REPO/logsafe.py" | tee -a "$LOG_FILE"
    local workflow_rc=${PIPESTATUS[0]}

    # The log cannot describe the commit that contains it, so its last line announces that step;
    # what the step itself prints (below) only goes to the screen.
    log "LOG PUBLISH: workflow_exit_code=$workflow_rc - this log is now being committed and pushed (that outcome is on screen only)" | python -u "$REPO/logsafe.py" | tee -a "$LOG_FILE" >/dev/null
    publish_log 2>&1 | python -u "$REPO/logsafe.py"
    return $workflow_rc
}

if [ "${KOSHVANI_INNER:-}" = "1" ]; then
    run_workflow
else
    run_outer
fi
exit $?
