#!/data/data/com.termux/files/usr/bin/env bash
# ==========================================
# Koshvani Daily Automation
# ==========================================
#
# The whole script lives in main() and is only run on the last line. Bash reads
# a script incrementally as it executes it, and the `git pull` below can replace
# this very file mid-run; parsing everything up front means a changed
# run_daily.sh can never corrupt the run that pulled it.

main() {

REPO="$HOME/koshvani-dashboard"
LOG_DIR="$REPO/logs"

cd "$REPO" || exit 1

START_TS=$(date +%s)

# ==========================================
# Daily Log
# ==========================================

mkdir -p "$LOG_DIR"

LOG_FILE="$LOG_DIR/daily-$(date +%Y-%m-%d).log"

# Delete logs older than 10 days
find "$LOG_DIR" -type f -name "daily-*.log" -mtime +10 -delete

# Show output on screen AND save to log
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "========================================"
echo "KOSHVANI JOB STARTED"
echo "Time: $(date)"
echo "========================================"


# ==========================================
# Check Git Status
# ==========================================

echo ""
echo "[1/6] Checking Git status..."

git status --short

STATUS_FILE="docs/data/crawler_status.json"
if [ -f "$STATUS_FILE" ] && grep -q '"overall_status": "RUNNING"' "$STATUS_FILE"; then
    echo "NOTE: the previous crawler execution never finished (its status file still says RUNNING)."
fi

# docs/data is machine-generated by scrape.py, and the scraper saves every
# scheme the moment it is scraped - so uncommitted changes left by an
# interrupted run (lost signal, Termux killed by Android, ...) are real,
# successfully scraped data, not junk. They used to be discarded here purely so
# that `git pull --rebase` would not refuse to run over unstaged changes; saving
# them as a commit satisfies the pull just as well without destroying anything.
if [ -n "$(git status --porcelain -- docs/data)" ]; then
    echo "Found uncommitted docs/data changes from an interrupted run."
    echo "Saving them as a commit instead of discarding them..."
    git add docs/data
    git commit -m "Save partial Koshvani data from an interrupted run"
    if [ $? -ne 0 ]; then
        echo "WARNING: could not commit the leftover data - leaving it untouched."
    fi
fi

# ==========================================
# Pull Latest Code
# ==========================================

echo ""
echo "[2/6] Pulling latest code from GitHub..."

git pull --rebase origin main

if [ $? -ne 0 ]; then
    echo ""
    echo "ERROR: Git pull failed."
    echo "Please check Git status."
    echo "Time: $(date)"
    echo "========================================"
    python telegram_alert.py error --start "$START_TS" --stage git-pull
    exit 1
fi

echo "Git pull successful."


# ==========================================
# Run Koshvani Scraper
# ==========================================

echo ""
echo "[3/6] Starting Koshvani scraper..."
echo "Time: $(date)"
echo ""

python scraper/scrape.py
SCRAPER_RC=$?

# The scraper exits non-zero only when the run was cut short (a fatal error,
# or it was interrupted). Every scheme it finished was already saved to disk,
# so that is never a reason to throw the data away: it is committed and
# pushed below, and the report says PARTIAL / ERROR.
echo ""
if [ $SCRAPER_RC -eq 0 ]; then
    echo "Koshvani scraper completed."
else
    echo "WARNING: the scraper stopped early (exit code $SCRAPER_RC)."
    echo "Everything it had already saved is kept and published below."
fi


# ==========================================
# Check Data Changes
# ==========================================

echo ""
echo "[4/6] Checking for data changes..."

# `git status --porcelain` (not `git diff`) so a brand-new, still untracked
# file such as the first crawler_status.json counts as a change too.
if [ -z "$(git status --porcelain -- docs/data)" ]; then

    echo "No data changes detected."
    echo "No GitHub update required."

    # Nothing left that could still fail before the run is done - safe to
    # validate results and notify now.
    echo ""
    echo "Validating scheme results and notifying..."
    python telegram_alert.py report --start "$START_TS"

    echo ""
    echo "========================================"
    if [ $SCRAPER_RC -eq 0 ]; then
        echo "KOSHVANI JOB COMPLETED"
        echo "Status: SUCCESS - NO DATA CHANGES"
    else
        echo "KOSHVANI JOB ENDED EARLY"
        echo "Status: INCOMPLETE - scraper exit code $SCRAPER_RC"
    fi
    echo "Time: $(date)"
    echo "========================================"

    [ $SCRAPER_RC -eq 0 ] && exit 0
    exit 1
fi

echo "Data changes detected."


# ==========================================
# Commit & Push
# ==========================================

echo ""
echo "[5/6] Committing updated Koshvani data..."

COMMIT_MESSAGE="Update Koshvani data"
if [ $SCRAPER_RC -ne 0 ]; then
    COMMIT_MESSAGE="Update Koshvani data (partial run - scraper stopped early)"
fi

git add docs/data

git commit -m "$COMMIT_MESSAGE"

if [ $? -ne 0 ]; then
    echo ""
    echo "ERROR: Git commit failed."
    echo "Time: $(date)"
    echo "========================================"
    python telegram_alert.py error --start "$START_TS" --stage git-commit
    exit 1
fi

echo "Commit successful."

echo ""
echo "Pushing to GitHub..."

git push origin main

if [ $? -ne 0 ]; then
    echo ""
    echo "ERROR: Git push failed."
    echo "Time: $(date)"
    echo "========================================"
    python telegram_alert.py error --start "$START_TS" --stage git-push
    exit 1
fi

echo ""
echo "GitHub push successful."


# ==========================================
# Validate Results & Notify
# ==========================================

# Only reached once the run is fully complete (pull, scraper, commit and
# push all done) - so the notification always reflects the real final
# outcome, never a SUCCESS sent before a later step could still fail.
echo ""
echo "[6/6] Validating scheme results and notifying..."

python telegram_alert.py report --start "$START_TS"


# ==========================================
# Finished
# ==========================================

echo ""
echo "========================================"
if [ $SCRAPER_RC -eq 0 ]; then
    echo "KOSHVANI JOB COMPLETED"
    echo "Status: SUCCESS"
else
    echo "KOSHVANI JOB ENDED EARLY"
    echo "Status: INCOMPLETE - partial data was published (scraper exit code $SCRAPER_RC)"
fi
echo "Time: $(date)"
echo "========================================"

[ $SCRAPER_RC -eq 0 ] && exit 0
exit 1

}

main "$@"
exit $?
